[package]
name = "vtracer_py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "vtracer_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
vtracer = "0.5.0"
visioncortex =  "0.8.0" 

